"""post_rich_text

Revision ID: 1a1e3833c544
Revises: 236b80ec2d98
Create Date: 2015-09-05 17:09:17.339000

"""

# revision identifiers, used by Alembic.
revision = '1a1e3833c544'
down_revision = '236b80ec2d98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
