"""add account confirm

Revision ID: d3e7ecd1428
Revises: 32ec529406af
Create Date: 2015-09-02 23:16:33.603000

"""

# revision identifiers, used by Alembic.
revision = 'd3e7ecd1428'
down_revision = '32ec529406af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
